FROM node:20

# Install build deps for sqlite3
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5000

# Run backend in dev mode
CMD ["node", "src/server.js"]
